"""Initial schema with image_metadata table

Revision ID: ecda9930aefa
Revises: 
Create Date: 2026-02-12 16:49:40.861212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecda9930aefa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('copyright', sa.String(length=200), nullable=False),
    sa.Column('dataset_release', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('data_processing_stages', sa.String(length=500), nullable=False),
    sa.Column('coordinates', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_filename'), 'image_metadata', ['filename'], unique=True)
    op.create_index(op.f('ix_image_metadata_id'), 'image_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_metadata_id'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_filename'), table_name='image_metadata')
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
